on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: gohelpinghands.azurecr.io
        username: ${{ secrets.acr_gohelpinghands_username }}
        password: ${{ secrets.acr_gohelpinghands_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/demo" -f  "demo/Dockerfile" -t gohelpinghands.azurecr.io/dimpy:${{ github.sha }} --label dockerfile-path=demo/Dockerfile
        docker push gohelpinghands.azurecr.io/dimpy:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_dimpy_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep dimpy9e00 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace dimpy9e00`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: dimpy9e00
        container-registry-url: gohelpinghands.azurecr.io
        container-registry-username: ${{ secrets.acr_gohelpinghands_username }}
        container-registry-password: ${{ secrets.acr_gohelpinghands_password }}
        secret-name: dimpydockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: dimpy9e00
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          gohelpinghands.azurecr.io/dimpy:${{ github.sha }}
        imagepullsecrets: |
          dimpydockerauth
